// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddDictionaryLinkData, AddDictionaryLinkErrors, AddDictionaryLinkResponses, AutocompleteWordsData, AutocompleteWordsErrors, AutocompleteWordsResponses, CreateRootData, CreateRootErrors, CreateRootResponses, CreateWordData, CreateWordErrors, CreateWordResponses, DeleteDictionaryLinkData, DeleteDictionaryLinkErrors, DeleteDictionaryLinkResponses, DeleteRootData, DeleteRootErrors, DeleteRootResponses, DeleteWordData, DeleteWordErrors, DeleteWordResponses, GenerateWordExamplesData, GenerateWordExamplesErrors, GenerateWordExamplesResponses, GetHealthData, GetHealthErrors, GetHealthResponses, GetRootByIdData, GetRootByIdErrors, GetRootByIdResponses, GetSwaggerUiData, GetSwaggerUiErrors, GetSwaggerUiResponses, GetWordByIdData, GetWordByIdErrors, GetWordByIdResponses, ListDictionaryLinksData, ListDictionaryLinksErrors, ListDictionaryLinksResponses, ListRootsData, ListRootsErrors, ListRootsResponses, ListWordsData, ListWordsErrors, ListWordsResponses, NormalizeRootData, NormalizeRootErrors, NormalizeRootResponses, UpdateRootData, UpdateRootErrors, UpdateRootResponses, UpdateWordData, UpdateWordErrors, UpdateWordResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Arabic roots
 */
export const listRoots = <ThrowOnError extends boolean = false>(options?: Options<ListRootsData, ThrowOnError>) => (options?.client ?? client).get<ListRootsResponses, ListRootsErrors, ThrowOnError>({ url: '/api/v1/roots', ...options });

/**
 * Create a new Arabic root
 */
export const createRoot = <ThrowOnError extends boolean = false>(options: Options<CreateRootData, ThrowOnError>) => (options.client ?? client).post<CreateRootResponses, CreateRootErrors, ThrowOnError>({
    url: '/api/v1/roots',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Normalize an Arabic root input without persisting it
 */
export const normalizeRoot = <ThrowOnError extends boolean = false>(options: Options<NormalizeRootData, ThrowOnError>) => (options.client ?? client).post<NormalizeRootResponses, NormalizeRootErrors, ThrowOnError>({
    url: '/api/v1/roots/normalize',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a root
 */
export const deleteRoot = <ThrowOnError extends boolean = false>(options: Options<DeleteRootData, ThrowOnError>) => (options.client ?? client).delete<DeleteRootResponses, DeleteRootErrors, ThrowOnError>({ url: '/api/v1/roots/{id}', ...options });

/**
 * Get a root by ID
 */
export const getRootById = <ThrowOnError extends boolean = false>(options: Options<GetRootByIdData, ThrowOnError>) => (options.client ?? client).get<GetRootByIdResponses, GetRootByIdErrors, ThrowOnError>({ url: '/api/v1/roots/{id}', ...options });

/**
 * Update a root's meaning or analysis
 */
export const updateRoot = <ThrowOnError extends boolean = false>(options: Options<UpdateRootData, ThrowOnError>) => (options.client ?? client).put<UpdateRootResponses, UpdateRootErrors, ThrowOnError>({
    url: '/api/v1/roots/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List vocabulary words with optional filters
 */
export const listWords = <ThrowOnError extends boolean = false>(options?: Options<ListWordsData, ThrowOnError>) => (options?.client ?? client).get<ListWordsResponses, ListWordsErrors, ThrowOnError>({ url: '/api/v1/words', ...options });

/**
 * Create a vocabulary word
 */
export const createWord = <ThrowOnError extends boolean = false>(options: Options<CreateWordData, ThrowOnError>) => (options.client ?? client).post<CreateWordResponses, CreateWordErrors, ThrowOnError>({
    url: '/api/v1/words',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Lightweight word search for linking operations
 */
export const autocompleteWords = <ThrowOnError extends boolean = false>(options: Options<AutocompleteWordsData, ThrowOnError>) => (options.client ?? client).get<AutocompleteWordsResponses, AutocompleteWordsErrors, ThrowOnError>({ url: '/api/v1/words/autocomplete', ...options });

/**
 * Delete a word
 */
export const deleteWord = <ThrowOnError extends boolean = false>(options: Options<DeleteWordData, ThrowOnError>) => (options.client ?? client).delete<DeleteWordResponses, DeleteWordErrors, ThrowOnError>({ url: '/api/v1/words/{id}', ...options });

/**
 * Get a word by ID
 */
export const getWordById = <ThrowOnError extends boolean = false>(options: Options<GetWordByIdData, ThrowOnError>) => (options.client ?? client).get<GetWordByIdResponses, GetWordByIdErrors, ThrowOnError>({ url: '/api/v1/words/{id}', ...options });

/**
 * Update a word (all fields optional — only provided fields change)
 */
export const updateWord = <ThrowOnError extends boolean = false>(options: Options<UpdateWordData, ThrowOnError>) => (options.client ?? client).put<UpdateWordResponses, UpdateWordErrors, ThrowOnError>({
    url: '/api/v1/words/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List dictionary links for a word
 */
export const listDictionaryLinks = <ThrowOnError extends boolean = false>(options: Options<ListDictionaryLinksData, ThrowOnError>) => (options.client ?? client).get<ListDictionaryLinksResponses, ListDictionaryLinksErrors, ThrowOnError>({ url: '/api/v1/words/{id}/dictionary-links', ...options });

/**
 * Add a dictionary link to a word
 */
export const addDictionaryLink = <ThrowOnError extends boolean = false>(options: Options<AddDictionaryLinkData, ThrowOnError>) => (options.client ?? client).post<AddDictionaryLinkResponses, AddDictionaryLinkErrors, ThrowOnError>({
    url: '/api/v1/words/{id}/dictionary-links',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Remove a dictionary link from a word
 */
export const deleteDictionaryLink = <ThrowOnError extends boolean = false>(options: Options<DeleteDictionaryLinkData, ThrowOnError>) => (options.client ?? client).delete<DeleteDictionaryLinkResponses, DeleteDictionaryLinkErrors, ThrowOnError>({ url: '/api/v1/words/{id}/dictionary-links/{linkId}', ...options });

/**
 * Generate AI example sentences for a word
 */
export const generateWordExamples = <ThrowOnError extends boolean = false>(options: Options<GenerateWordExamplesData, ThrowOnError>) => (options.client ?? client).post<GenerateWordExamplesResponses, GenerateWordExamplesErrors, ThrowOnError>({ url: '/api/v1/words/{id}/examples', ...options });

/**
 * Health check
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, GetHealthErrors, ThrowOnError>({ url: '/health', ...options });

/**
 * Swagger UI
 */
export const getSwaggerUi = <ThrowOnError extends boolean = false>(options?: Options<GetSwaggerUiData, ThrowOnError>) => (options?.client ?? client).get<GetSwaggerUiResponses, GetSwaggerUiErrors, ThrowOnError>({ url: '/api/v1/swagger-ui', ...options });
