// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8085' | (string & {});
};

export type HealthResponse = {
    status: string;
};

export type RootResponse = {
    id: string;
    letters: Array<string>;
    normalizedForm: string;
    displayForm: string;
    letterCount: number;
    meaning?: string | null;
    analysis?: string | null;
    createdAt: string;
    updatedAt: string;
};

export type CreateRootRequest = {
    /**
     * Letters in any format: space/dash/comma-separated or concatenated
     */
    root: string;
    meaning?: string | null;
    analysis?: string | null;
};

export type UpdateRootRequest = {
    meaning?: string | null;
    analysis?: string | null;
};

export type NormalizeRequest = {
    /**
     * Letters in any supported format: space-separated, dash-separated, comma-separated, or concatenated
     */
    input: string;
};

export type NormalizeResponse = {
    letters: Array<string>;
    normalizedForm: string;
    displayForm: string;
    letterCount: number;
};

export type WordResponse = {
    id: string;
    arabicText: string;
    transliteration?: string | null;
    translation?: string | null;
    exampleSentence?: string | null;
    partOfSpeech: PartOfSpeech;
    dialect: Dialect;
    difficulty: Difficulty;
    masteryLevel: MasteryLevel;
    pronunciationUrl?: string | null;
    rootId?: string | null;
    derivedFromId?: string | null;
    createdAt: string;
    updatedAt: string;
};

export type CreateWordRequest = {
    arabicText: string;
    transliteration?: string | null;
    translation?: string | null;
    exampleSentence?: string | null;
    partOfSpeech?: PartOfSpeech;
    dialect?: Dialect;
    difficulty?: Difficulty;
    pronunciationUrl?: string | null;
    rootId?: string | null;
    derivedFromId?: string | null;
};

/**
 * All fields optional — only provided fields are updated
 */
export type UpdateWordRequest = {
    arabicText?: string | null;
    transliteration?: string | null;
    translation?: string | null;
    exampleSentence?: string | null;
    partOfSpeech?: PartOfSpeech | null;
    dialect?: Dialect | null;
    difficulty?: Difficulty | null;
    masteryLevel?: MasteryLevel | null;
    pronunciationUrl?: string | null;
    rootId?: string | null;
    derivedFromId?: string | null;
};

export type WordAutocompleteResponse = {
    id: string;
    arabicText: string;
    translation?: string | null;
};

export type DictionaryLinkResponse = {
    id: string;
    source: DictionarySource;
    url: string;
};

export type CreateDictionaryLinkRequest = {
    source: DictionarySource;
    url: string;
};

export type ExampleSentenceResponse = {
    arabic: string;
    transliteration: string;
    translation: string;
};

export type ExamplesResponse = {
    examples: Array<ExampleSentenceResponse>;
};

export type TextResponse = {
    id: string;
    title: string;
    /**
     * Arabic body content
     */
    body: string;
    transliteration?: string | null;
    translation?: string | null;
    difficulty: Difficulty;
    dialect: Dialect;
    /**
     * Freetext notes about the text
     */
    comments?: string | null;
    tags: Array<string>;
    createdAt: string;
    updatedAt: string;
};

export type CreateTextRequest = {
    title: string;
    /**
     * Arabic body content
     */
    body: string;
    transliteration?: string | null;
    translation?: string | null;
    difficulty?: Difficulty;
    dialect?: Dialect;
    comments?: string | null;
    tags?: Array<string>;
};

/**
 * All fields optional — only provided fields are updated
 */
export type UpdateTextRequest = {
    title?: string | null;
    body?: string | null;
    transliteration?: string | null;
    translation?: string | null;
    difficulty?: Difficulty | null;
    dialect?: Dialect | null;
    comments?: string | null;
    tags?: Array<string> | null;
};

export type SummarizeResponse = {
    /**
     * AI-generated summary of the text
     */
    summary: string;
};

export type AlignmentTokenResponse = {
    id: string;
    sentenceId: string;
    position: number;
    arabic: string;
    transliteration?: string | null;
    translation?: string | null;
    wordId?: string | null;
};

export type SentenceResponse = {
    id: string;
    textId: string;
    /**
     * 1-based ordering within the text
     */
    position: number;
    arabicText: string;
    transliteration?: string | null;
    freeTranslation?: string | null;
    notes?: string | null;
    /**
     * False when arabicText was edited after tokenization
     */
    tokensValid: boolean;
    tokens: Array<AlignmentTokenResponse>;
    createdAt: string;
    updatedAt: string;
};

export type CreateSentenceRequest = {
    arabicText: string;
    /**
     * Insertion position (appended at end if omitted)
     */
    position?: number | null;
    transliteration?: string | null;
    freeTranslation?: string | null;
    notes?: string | null;
};

/**
 * All fields optional — only provided fields are updated
 */
export type UpdateSentenceRequest = {
    arabicText?: string | null;
    position?: number | null;
    transliteration?: string | null;
    freeTranslation?: string | null;
    notes?: string | null;
};

export type ReplaceTokensRequest = {
    tokens: Array<{
        position: number;
        arabic: string;
        transliteration?: string | null;
        translation?: string | null;
        wordId?: string | null;
    }>;
};

export type AnnotationResponse = {
    id: string;
    textId: string;
    /**
     * The anchored text fragment this annotation refers to
     */
    anchor: string;
    type: 'VOCAB' | 'GRAMMAR' | 'CULTURAL' | 'STRUCTURE';
    content?: string | null;
    masteryLevel?: 'NEW' | 'LEARNING' | 'KNOWN' | 'MASTERED';
    reviewFlag: boolean;
    linkedWordIds: Array<string>;
    createdAt: string;
    updatedAt: string;
};

export type CreateAnnotationRequest = {
    anchor: string;
    type: 'VOCAB' | 'GRAMMAR' | 'CULTURAL' | 'STRUCTURE';
    content?: string | null;
    masteryLevel?: 'NEW' | 'LEARNING' | 'KNOWN' | 'MASTERED';
    reviewFlag?: boolean;
    linkedWordIds?: Array<string>;
};

/**
 * All fields optional — only provided fields are updated
 */
export type UpdateAnnotationRequest = {
    anchor?: string | null;
    type?: 'VOCAB' | 'GRAMMAR' | 'CULTURAL' | 'STRUCTURE';
    content?: string | null;
    masteryLevel?: 'NEW' | 'LEARNING' | 'KNOWN' | 'MASTERED';
    reviewFlag?: boolean | null;
};

export type PartOfSpeech = 'UNKNOWN' | 'NOUN' | 'VERB' | 'ADJECTIVE' | 'ADVERB' | 'PREPOSITION' | 'PARTICLE' | 'INTERJECTION' | 'CONJUNCTION' | 'PRONOUN';

export type Dialect = 'TUNISIAN' | 'MOROCCAN' | 'EGYPTIAN' | 'GULF' | 'LEVANTINE' | 'MSA' | 'IRAQI';

export type Difficulty = 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';

export type MasteryLevel = 'NEW' | 'LEARNING' | 'KNOWN' | 'MASTERED';

export type DictionarySource = 'ALMANY' | 'LIVING_ARABIC' | 'DERJA_NINJA' | 'REVERSO' | 'WIKTIONARY' | 'ARABIC_STUDENT_DICTIONARY' | 'LANGENSCHEIDT' | 'CUSTOM';

export type ErrorResponse = {
    /**
     * Human-readable error message
     */
    error: string;
    /**
     * Machine-readable error code
     */
    code: string;
};

export type PaginatedResponse = {
    items: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Total number of matching records
     */
    total: number;
    /**
     * Current page (1-based)
     */
    page: number;
    /**
     * Page size requested
     */
    size: number;
};

export type TransliterateRequest = {
    /**
     * Arabic text to transliterate
     */
    arabic: string;
};

export type TransliterateResponse = {
    /**
     * Chat-alphabet transliteration of the input
     */
    transliteration?: string;
};

export type ListRootsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        size?: number;
        /**
         * Filter by number of root letters (2–6)
         */
        letterCount?: number;
    };
    url: '/api/v1/roots';
};

export type ListRootsErrors = {
    /**
     * Invalid query parameters
     */
    400: ErrorResponse;
};

export type ListRootsError = ListRootsErrors[keyof ListRootsErrors];

export type ListRootsResponses = {
    /**
     * Paginated list of roots
     */
    200: PaginatedResponse & {
        items?: Array<RootResponse>;
    };
};

export type ListRootsResponse = ListRootsResponses[keyof ListRootsResponses];

export type CreateRootData = {
    body: CreateRootRequest;
    path?: never;
    query?: never;
    url: '/api/v1/roots';
};

export type CreateRootErrors = {
    /**
     * Invalid input
     */
    400: ErrorResponse;
    /**
     * Root already exists
     */
    409: ErrorResponse;
};

export type CreateRootError = CreateRootErrors[keyof CreateRootErrors];

export type CreateRootResponses = {
    /**
     * Root created
     */
    201: RootResponse;
};

export type CreateRootResponse = CreateRootResponses[keyof CreateRootResponses];

export type NormalizeRootData = {
    body: NormalizeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/roots/normalize';
};

export type NormalizeRootErrors = {
    /**
     * Invalid input
     */
    400: ErrorResponse;
};

export type NormalizeRootError = NormalizeRootErrors[keyof NormalizeRootErrors];

export type NormalizeRootResponses = {
    /**
     * Normalized form
     */
    200: NormalizeResponse;
};

export type NormalizeRootResponse = NormalizeRootResponses[keyof NormalizeRootResponses];

export type DeleteRootData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/roots/{id}';
};

export type DeleteRootErrors = {
    /**
     * Root not found
     */
    404: ErrorResponse;
};

export type DeleteRootError = DeleteRootErrors[keyof DeleteRootErrors];

export type DeleteRootResponses = {
    /**
     * Root deleted
     */
    204: void;
};

export type DeleteRootResponse = DeleteRootResponses[keyof DeleteRootResponses];

export type GetRootByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/roots/{id}';
};

export type GetRootByIdErrors = {
    /**
     * Malformed UUID
     */
    400: ErrorResponse;
    /**
     * Root not found
     */
    404: ErrorResponse;
};

export type GetRootByIdError = GetRootByIdErrors[keyof GetRootByIdErrors];

export type GetRootByIdResponses = {
    /**
     * Root found
     */
    200: RootResponse;
};

export type GetRootByIdResponse = GetRootByIdResponses[keyof GetRootByIdResponses];

export type UpdateRootData = {
    body: UpdateRootRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/roots/{id}';
};

export type UpdateRootErrors = {
    /**
     * Root not found
     */
    404: ErrorResponse;
};

export type UpdateRootError = UpdateRootErrors[keyof UpdateRootErrors];

export type UpdateRootResponses = {
    /**
     * Root updated
     */
    200: RootResponse;
};

export type UpdateRootResponse = UpdateRootResponses[keyof UpdateRootResponses];

export type ListWordsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        size?: number;
        /**
         * Arabic text substring search
         */
        q?: string;
        dialect?: Dialect;
        difficulty?: Difficulty;
        partOfSpeech?: PartOfSpeech;
        masteryLevel?: MasteryLevel;
    };
    url: '/api/v1/words';
};

export type ListWordsErrors = {
    /**
     * Invalid query parameters
     */
    400: ErrorResponse;
};

export type ListWordsError = ListWordsErrors[keyof ListWordsErrors];

export type ListWordsResponses = {
    /**
     * Paginated list of words
     */
    200: PaginatedResponse & {
        items?: Array<WordResponse>;
    };
};

export type ListWordsResponse = ListWordsResponses[keyof ListWordsResponses];

export type CreateWordData = {
    body: CreateWordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/words';
};

export type CreateWordErrors = {
    /**
     * Validation error (blank arabicText, unknown enum value)
     */
    422: ErrorResponse;
};

export type CreateWordError = CreateWordErrors[keyof CreateWordErrors];

export type CreateWordResponses = {
    /**
     * Word created
     */
    201: WordResponse;
};

export type CreateWordResponse = CreateWordResponses[keyof CreateWordResponses];

export type AutocompleteWordsData = {
    body?: never;
    path?: never;
    query: {
        q: string;
        limit?: number;
    };
    url: '/api/v1/words/autocomplete';
};

export type AutocompleteWordsErrors = {
    /**
     * Missing required query parameter `q`
     */
    400: ErrorResponse;
};

export type AutocompleteWordsError = AutocompleteWordsErrors[keyof AutocompleteWordsErrors];

export type AutocompleteWordsResponses = {
    /**
     * Matching words (id + arabicText + translation only)
     */
    200: Array<WordAutocompleteResponse>;
};

export type AutocompleteWordsResponse = AutocompleteWordsResponses[keyof AutocompleteWordsResponses];

export type DeleteWordData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/words/{id}';
};

export type DeleteWordErrors = {
    /**
     * Word not found
     */
    404: ErrorResponse;
};

export type DeleteWordError = DeleteWordErrors[keyof DeleteWordErrors];

export type DeleteWordResponses = {
    /**
     * Word deleted
     */
    204: void;
};

export type DeleteWordResponse = DeleteWordResponses[keyof DeleteWordResponses];

export type GetWordByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/words/{id}';
};

export type GetWordByIdErrors = {
    /**
     * Malformed UUID
     */
    400: ErrorResponse;
    /**
     * Word not found
     */
    404: ErrorResponse;
};

export type GetWordByIdError = GetWordByIdErrors[keyof GetWordByIdErrors];

export type GetWordByIdResponses = {
    /**
     * Word found
     */
    200: WordResponse;
};

export type GetWordByIdResponse = GetWordByIdResponses[keyof GetWordByIdResponses];

export type UpdateWordData = {
    body: UpdateWordRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/words/{id}';
};

export type UpdateWordErrors = {
    /**
     * Word not found
     */
    404: ErrorResponse;
    /**
     * Validation error
     */
    422: ErrorResponse;
};

export type UpdateWordError = UpdateWordErrors[keyof UpdateWordErrors];

export type UpdateWordResponses = {
    /**
     * Word updated
     */
    200: WordResponse;
};

export type UpdateWordResponse = UpdateWordResponses[keyof UpdateWordResponses];

export type ListDictionaryLinksData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/words/{id}/dictionary-links';
};

export type ListDictionaryLinksErrors = {
    /**
     * Word not found
     */
    404: ErrorResponse;
};

export type ListDictionaryLinksError = ListDictionaryLinksErrors[keyof ListDictionaryLinksErrors];

export type ListDictionaryLinksResponses = {
    /**
     * List of dictionary links
     */
    200: Array<DictionaryLinkResponse>;
};

export type ListDictionaryLinksResponse = ListDictionaryLinksResponses[keyof ListDictionaryLinksResponses];

export type AddDictionaryLinkData = {
    body: CreateDictionaryLinkRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/words/{id}/dictionary-links';
};

export type AddDictionaryLinkErrors = {
    /**
     * Word not found
     */
    404: ErrorResponse;
    /**
     * Unknown dictionary source
     */
    422: ErrorResponse;
};

export type AddDictionaryLinkError = AddDictionaryLinkErrors[keyof AddDictionaryLinkErrors];

export type AddDictionaryLinkResponses = {
    /**
     * Link added
     */
    201: DictionaryLinkResponse;
};

export type AddDictionaryLinkResponse = AddDictionaryLinkResponses[keyof AddDictionaryLinkResponses];

export type DeleteDictionaryLinkData = {
    body?: never;
    path: {
        id: string;
        linkId: string;
    };
    query?: never;
    url: '/api/v1/words/{id}/dictionary-links/{linkId}';
};

export type DeleteDictionaryLinkErrors = {
    /**
     * Word or link not found
     */
    404: ErrorResponse;
};

export type DeleteDictionaryLinkError = DeleteDictionaryLinkErrors[keyof DeleteDictionaryLinkErrors];

export type DeleteDictionaryLinkResponses = {
    /**
     * Link removed
     */
    204: void;
};

export type DeleteDictionaryLinkResponse = DeleteDictionaryLinkResponses[keyof DeleteDictionaryLinkResponses];

export type GenerateWordExamplesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/words/{id}/examples';
};

export type GenerateWordExamplesErrors = {
    /**
     * Word not found
     */
    404: ErrorResponse;
    /**
     * AI not configured (OPENROUTER_API_KEY missing)
     */
    503: ErrorResponse;
};

export type GenerateWordExamplesError = GenerateWordExamplesErrors[keyof GenerateWordExamplesErrors];

export type GenerateWordExamplesResponses = {
    /**
     * Two example sentences
     */
    200: ExamplesResponse;
};

export type GenerateWordExamplesResponse = GenerateWordExamplesResponses[keyof GenerateWordExamplesResponses];

export type ListTextsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        size?: number;
        /**
         * Free-text search across title and body
         */
        q?: string;
        dialect?: Dialect;
        difficulty?: Difficulty;
        /**
         * Filter by tag (exact match)
         */
        tag?: string;
    };
    url: '/api/v1/texts';
};

export type ListTextsErrors = {
    /**
     * Invalid query parameters
     */
    400: ErrorResponse;
};

export type ListTextsError = ListTextsErrors[keyof ListTextsErrors];

export type ListTextsResponses = {
    /**
     * Paginated list of texts
     */
    200: PaginatedResponse & {
        items?: Array<TextResponse>;
    };
};

export type ListTextsResponse = ListTextsResponses[keyof ListTextsResponses];

export type CreateTextData = {
    body: CreateTextRequest;
    path?: never;
    query?: never;
    url: '/api/v1/texts';
};

export type CreateTextErrors = {
    /**
     * Validation error (blank title or body)
     */
    422: ErrorResponse;
};

export type CreateTextError = CreateTextErrors[keyof CreateTextErrors];

export type CreateTextResponses = {
    /**
     * Text created
     */
    201: TextResponse;
};

export type CreateTextResponse = CreateTextResponses[keyof CreateTextResponses];

export type DeleteTextData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/texts/{id}';
};

export type DeleteTextErrors = {
    /**
     * Text not found
     */
    404: ErrorResponse;
};

export type DeleteTextError = DeleteTextErrors[keyof DeleteTextErrors];

export type DeleteTextResponses = {
    /**
     * Text deleted
     */
    204: void;
};

export type DeleteTextResponse = DeleteTextResponses[keyof DeleteTextResponses];

export type GetTextByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/texts/{id}';
};

export type GetTextByIdErrors = {
    /**
     * Malformed UUID
     */
    400: ErrorResponse;
    /**
     * Text not found
     */
    404: ErrorResponse;
};

export type GetTextByIdError = GetTextByIdErrors[keyof GetTextByIdErrors];

export type GetTextByIdResponses = {
    /**
     * Text found
     */
    200: TextResponse;
};

export type GetTextByIdResponse = GetTextByIdResponses[keyof GetTextByIdResponses];

export type UpdateTextData = {
    body: UpdateTextRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/texts/{id}';
};

export type UpdateTextErrors = {
    /**
     * Text not found
     */
    404: ErrorResponse;
    /**
     * Validation error
     */
    422: ErrorResponse;
};

export type UpdateTextError = UpdateTextErrors[keyof UpdateTextErrors];

export type UpdateTextResponses = {
    /**
     * Text updated
     */
    200: TextResponse;
};

export type UpdateTextResponse = UpdateTextResponses[keyof UpdateTextResponses];

export type SummarizeTextData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/texts/{id}/summarize';
};

export type SummarizeTextErrors = {
    /**
     * Text not found
     */
    404: ErrorResponse;
    /**
     * AI not configured (OPENROUTER_API_KEY missing)
     */
    503: ErrorResponse;
};

export type SummarizeTextError = SummarizeTextErrors[keyof SummarizeTextErrors];

export type SummarizeTextResponses = {
    /**
     * Generated summary
     */
    200: SummarizeResponse;
};

export type SummarizeTextResponse = SummarizeTextResponses[keyof SummarizeTextResponses];

export type ListSentencesData = {
    body?: never;
    path: {
        textId: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/sentences';
};

export type ListSentencesErrors = {
    /**
     * Text not found
     */
    404: ErrorResponse;
};

export type ListSentencesError = ListSentencesErrors[keyof ListSentencesErrors];

export type ListSentencesResponses = {
    /**
     * Array of sentences (no pagination)
     */
    200: Array<SentenceResponse>;
};

export type ListSentencesResponse = ListSentencesResponses[keyof ListSentencesResponses];

export type CreateSentenceData = {
    body: CreateSentenceRequest;
    path: {
        textId: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/sentences';
};

export type CreateSentenceErrors = {
    /**
     * Text not found
     */
    404: ErrorResponse;
    /**
     * Validation error (blank arabicText, unknown enum value)
     */
    422: ErrorResponse;
};

export type CreateSentenceError = CreateSentenceErrors[keyof CreateSentenceErrors];

export type CreateSentenceResponses = {
    /**
     * Sentence created
     */
    201: SentenceResponse;
};

export type CreateSentenceResponse = CreateSentenceResponses[keyof CreateSentenceResponses];

export type DeleteSentenceData = {
    body?: never;
    path: {
        textId: string;
        id: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/sentences/{id}';
};

export type DeleteSentenceErrors = {
    /**
     * Sentence or text not found
     */
    404: ErrorResponse;
};

export type DeleteSentenceError = DeleteSentenceErrors[keyof DeleteSentenceErrors];

export type DeleteSentenceResponses = {
    /**
     * Sentence deleted
     */
    204: void;
};

export type DeleteSentenceResponse = DeleteSentenceResponses[keyof DeleteSentenceResponses];

export type GetSentenceByIdData = {
    body?: never;
    path: {
        textId: string;
        id: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/sentences/{id}';
};

export type GetSentenceByIdErrors = {
    /**
     * Malformed UUID
     */
    400: ErrorResponse;
    /**
     * Sentence or text not found
     */
    404: ErrorResponse;
};

export type GetSentenceByIdError = GetSentenceByIdErrors[keyof GetSentenceByIdErrors];

export type GetSentenceByIdResponses = {
    /**
     * Sentence found
     */
    200: SentenceResponse;
};

export type GetSentenceByIdResponse = GetSentenceByIdResponses[keyof GetSentenceByIdResponses];

export type UpdateSentenceData = {
    body: UpdateSentenceRequest;
    path: {
        textId: string;
        id: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/sentences/{id}';
};

export type UpdateSentenceErrors = {
    /**
     * Sentence or text not found
     */
    404: ErrorResponse;
    /**
     * Validation error
     */
    422: ErrorResponse;
};

export type UpdateSentenceError = UpdateSentenceErrors[keyof UpdateSentenceErrors];

export type UpdateSentenceResponses = {
    /**
     * Sentence updated
     */
    200: SentenceResponse;
};

export type UpdateSentenceResponse = UpdateSentenceResponses[keyof UpdateSentenceResponses];

export type ClearTokensData = {
    body?: never;
    path: {
        textId: string;
        id: string;
    };
    query: {
        /**
         * Must be set to "true" to confirm clearing tokens
         */
        confirm: 'true';
    };
    url: '/api/v1/texts/{textId}/sentences/{id}/tokens';
};

export type ClearTokensErrors = {
    /**
     * Missing or invalid confirm parameter
     */
    400: ErrorResponse;
    /**
     * Sentence or text not found
     */
    404: ErrorResponse;
};

export type ClearTokensError = ClearTokensErrors[keyof ClearTokensErrors];

export type ClearTokensResponses = {
    /**
     * Tokens cleared
     */
    200: SentenceResponse;
};

export type ClearTokensResponse = ClearTokensResponses[keyof ClearTokensResponses];

export type ReplaceTokensData = {
    body: ReplaceTokensRequest;
    path: {
        textId: string;
        id: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/sentences/{id}/tokens';
};

export type ReplaceTokensErrors = {
    /**
     * Sentence or text not found
     */
    404: ErrorResponse;
};

export type ReplaceTokensError = ReplaceTokensErrors[keyof ReplaceTokensErrors];

export type ReplaceTokensResponses = {
    /**
     * Tokens replaced
     */
    200: SentenceResponse;
};

export type ReplaceTokensResponse = ReplaceTokensResponses[keyof ReplaceTokensResponses];

export type AutoTokenizeData = {
    body?: never;
    path: {
        textId: string;
        id: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/sentences/{id}/auto-tokenize';
};

export type AutoTokenizeErrors = {
    /**
     * Sentence or text not found
     */
    404: ErrorResponse;
    /**
     * AI not configured (OPENROUTER_API_KEY missing)
     */
    503: ErrorResponse;
};

export type AutoTokenizeError = AutoTokenizeErrors[keyof AutoTokenizeErrors];

export type AutoTokenizeResponses = {
    /**
     * Tokens generated and set
     */
    200: SentenceResponse;
};

export type AutoTokenizeResponse = AutoTokenizeResponses[keyof AutoTokenizeResponses];

export type TransliterateSentenceData = {
    body?: never;
    path: {
        textId: string;
        id: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/sentences/{id}/transliterate';
};

export type TransliterateSentenceErrors = {
    /**
     * Sentence or text not found
     */
    404: ErrorResponse;
    /**
     * AI not configured (OPENROUTER_API_KEY missing)
     */
    503: ErrorResponse;
};

export type TransliterateSentenceError = TransliterateSentenceErrors[keyof TransliterateSentenceErrors];

export type TransliterateSentenceResponses = {
    /**
     * Transliteration generated and set
     */
    200: SentenceResponse;
};

export type TransliterateSentenceResponse = TransliterateSentenceResponses[keyof TransliterateSentenceResponses];

export type ListAnnotationsData = {
    body?: never;
    path: {
        textId: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/annotations';
};

export type ListAnnotationsErrors = {
    /**
     * Malformed UUID
     */
    400: ErrorResponse;
};

export type ListAnnotationsError = ListAnnotationsErrors[keyof ListAnnotationsErrors];

export type ListAnnotationsResponses = {
    /**
     * List of annotations
     */
    200: Array<AnnotationResponse>;
};

export type ListAnnotationsResponse = ListAnnotationsResponses[keyof ListAnnotationsResponses];

export type CreateAnnotationData = {
    body: CreateAnnotationRequest;
    path: {
        textId: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/annotations';
};

export type CreateAnnotationErrors = {
    /**
     * Text not found
     */
    404: ErrorResponse;
    /**
     * Validation error (blank anchor, unknown type)
     */
    422: ErrorResponse;
};

export type CreateAnnotationError = CreateAnnotationErrors[keyof CreateAnnotationErrors];

export type CreateAnnotationResponses = {
    /**
     * Annotation created
     */
    201: AnnotationResponse;
};

export type CreateAnnotationResponse = CreateAnnotationResponses[keyof CreateAnnotationResponses];

export type DeleteAnnotationData = {
    body?: never;
    path: {
        textId: string;
        id: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/annotations/{id}';
};

export type DeleteAnnotationErrors = {
    /**
     * Annotation or text not found
     */
    404: ErrorResponse;
};

export type DeleteAnnotationError = DeleteAnnotationErrors[keyof DeleteAnnotationErrors];

export type DeleteAnnotationResponses = {
    /**
     * Annotation deleted
     */
    204: void;
};

export type DeleteAnnotationResponse = DeleteAnnotationResponses[keyof DeleteAnnotationResponses];

export type GetAnnotationByIdData = {
    body?: never;
    path: {
        textId: string;
        id: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/annotations/{id}';
};

export type GetAnnotationByIdErrors = {
    /**
     * Annotation or text not found
     */
    404: ErrorResponse;
};

export type GetAnnotationByIdError = GetAnnotationByIdErrors[keyof GetAnnotationByIdErrors];

export type GetAnnotationByIdResponses = {
    /**
     * Annotation found
     */
    200: AnnotationResponse;
};

export type GetAnnotationByIdResponse = GetAnnotationByIdResponses[keyof GetAnnotationByIdResponses];

export type UpdateAnnotationData = {
    body: UpdateAnnotationRequest;
    path: {
        textId: string;
        id: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/annotations/{id}';
};

export type UpdateAnnotationErrors = {
    /**
     * Annotation or text not found
     */
    404: ErrorResponse;
    /**
     * Validation error
     */
    422: ErrorResponse;
};

export type UpdateAnnotationError = UpdateAnnotationErrors[keyof UpdateAnnotationErrors];

export type UpdateAnnotationResponses = {
    /**
     * Annotation updated
     */
    200: AnnotationResponse;
};

export type UpdateAnnotationResponse = UpdateAnnotationResponses[keyof UpdateAnnotationResponses];

export type AddWordLinkData = {
    body: {
        wordId: string;
    };
    path: {
        textId: string;
        id: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/annotations/{id}/words';
};

export type AddWordLinkErrors = {
    /**
     * Annotation or word not found
     */
    404: ErrorResponse;
};

export type AddWordLinkError = AddWordLinkErrors[keyof AddWordLinkErrors];

export type AddWordLinkResponses = {
    /**
     * Word linked, returns updated annotation
     */
    200: AnnotationResponse;
};

export type AddWordLinkResponse = AddWordLinkResponses[keyof AddWordLinkResponses];

export type RemoveWordLinkData = {
    body?: never;
    path: {
        textId: string;
        id: string;
        wordId: string;
    };
    query?: never;
    url: '/api/v1/texts/{textId}/annotations/{id}/words/{wordId}';
};

export type RemoveWordLinkErrors = {
    /**
     * Annotation or word not found
     */
    404: ErrorResponse;
};

export type RemoveWordLinkError = RemoveWordLinkErrors[keyof RemoveWordLinkErrors];

export type RemoveWordLinkResponses = {
    /**
     * Word link removed, returns updated annotation
     */
    200: AnnotationResponse;
};

export type RemoveWordLinkResponse = RemoveWordLinkResponses[keyof RemoveWordLinkResponses];

export type GetAnnotationsForWordData = {
    body?: never;
    path: {
        wordId: string;
    };
    query?: never;
    url: '/api/v1/words/{wordId}/annotations';
};

export type GetAnnotationsForWordErrors = {
    /**
     * Malformed UUID
     */
    400: ErrorResponse;
};

export type GetAnnotationsForWordError = GetAnnotationsForWordErrors[keyof GetAnnotationsForWordErrors];

export type GetAnnotationsForWordResponses = {
    /**
     * List of annotations linked to the word
     */
    200: Array<AnnotationResponse>;
};

export type GetAnnotationsForWordResponse = GetAnnotationsForWordResponses[keyof GetAnnotationsForWordResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthErrors = {
    /**
     * Bad request
     */
    400: unknown;
};

export type GetHealthResponses = {
    /**
     * Server is healthy
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetSwaggerUiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/swagger-ui';
};

export type GetSwaggerUiErrors = {
    /**
     * Bad request
     */
    400: unknown;
};

export type GetSwaggerUiResponses = {
    /**
     * Swagger UI HTML
     */
    200: unknown;
};

export type TransliterateTextData = {
    body: TransliterateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/transliterate';
};

export type TransliterateTextErrors = {
    /**
     * Validation error
     */
    422: unknown;
};

export type TransliterateTextResponses = {
    /**
     * Transliteration result
     */
    200: TransliterateResponse;
};

export type TransliterateTextResponse = TransliterateTextResponses[keyof TransliterateTextResponses];
