// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8085' | (string & {});
};

export type HealthResponse = {
    status: string;
};

export type RootResponse = {
    id: string;
    letters: Array<string>;
    normalizedForm: string;
    displayForm: string;
    letterCount: number;
    meaning?: string | null;
    analysis?: string | null;
    createdAt: string;
    updatedAt: string;
};

export type CreateRootRequest = {
    /**
     * Letters in any format: space/dash/comma-separated or concatenated
     */
    root: string;
    meaning?: string | null;
    analysis?: string | null;
};

export type UpdateRootRequest = {
    meaning?: string | null;
    analysis?: string | null;
};

export type NormalizeRequest = {
    /**
     * Letters in any supported format: space-separated, dash-separated, comma-separated, or concatenated
     */
    input: string;
};

export type NormalizeResponse = {
    letters: Array<string>;
    normalizedForm: string;
    displayForm: string;
    letterCount: number;
};

export type WordResponse = {
    id: string;
    arabicText: string;
    transliteration?: string | null;
    translation?: string | null;
    exampleSentence?: string | null;
    partOfSpeech: PartOfSpeech;
    dialect: Dialect;
    difficulty: Difficulty;
    masteryLevel: MasteryLevel;
    pronunciationUrl?: string | null;
    rootId?: string | null;
    derivedFromId?: string | null;
    createdAt: string;
    updatedAt: string;
};

export type CreateWordRequest = {
    arabicText: string;
    transliteration?: string | null;
    translation?: string | null;
    exampleSentence?: string | null;
    partOfSpeech?: PartOfSpeech;
    dialect?: Dialect;
    difficulty?: Difficulty;
    pronunciationUrl?: string | null;
    rootId?: string | null;
    derivedFromId?: string | null;
};

/**
 * All fields optional — only provided fields are updated
 */
export type UpdateWordRequest = {
    arabicText?: string | null;
    transliteration?: string | null;
    translation?: string | null;
    exampleSentence?: string | null;
    partOfSpeech?: PartOfSpeech | null;
    dialect?: Dialect | null;
    difficulty?: Difficulty | null;
    masteryLevel?: MasteryLevel | null;
    pronunciationUrl?: string | null;
    rootId?: string | null;
    derivedFromId?: string | null;
};

export type WordAutocompleteResponse = {
    id: string;
    arabicText: string;
    translation?: string | null;
};

export type DictionaryLinkResponse = {
    id: string;
    source: DictionarySource;
    url: string;
};

export type CreateDictionaryLinkRequest = {
    source: DictionarySource;
    url: string;
};

export type ExampleSentenceResponse = {
    arabic: string;
    transliteration: string;
    translation: string;
};

export type ExamplesResponse = {
    examples: Array<ExampleSentenceResponse>;
};

export type PartOfSpeech = 'UNKNOWN' | 'NOUN' | 'VERB' | 'ADJECTIVE' | 'ADVERB' | 'PREPOSITION' | 'PARTICLE' | 'INTERJECTION' | 'CONJUNCTION' | 'PRONOUN';

export type Dialect = 'TUNISIAN' | 'MOROCCAN' | 'EGYPTIAN' | 'GULF' | 'LEVANTINE' | 'MSA' | 'IRAQI';

export type Difficulty = 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';

export type MasteryLevel = 'NEW' | 'LEARNING' | 'KNOWN' | 'MASTERED';

export type DictionarySource = 'ALMANY' | 'LIVING_ARABIC' | 'DERJA_NINJA' | 'REVERSO' | 'WIKTIONARY' | 'ARABIC_STUDENT_DICTIONARY' | 'LANGENSCHEIDT' | 'CUSTOM';

export type ErrorResponse = {
    /**
     * Human-readable error message
     */
    error: string;
    /**
     * Machine-readable error code
     */
    code: string;
};

export type PaginatedResponse = {
    items: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Total number of matching records
     */
    total: number;
    /**
     * Current page (1-based)
     */
    page: number;
    /**
     * Page size requested
     */
    size: number;
};

export type ListRootsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        size?: number;
        /**
         * Filter by number of root letters (2–6)
         */
        letterCount?: number;
    };
    url: '/api/v1/roots';
};

export type ListRootsErrors = {
    /**
     * Invalid query parameters
     */
    400: ErrorResponse;
};

export type ListRootsError = ListRootsErrors[keyof ListRootsErrors];

export type ListRootsResponses = {
    /**
     * Paginated list of roots
     */
    200: PaginatedResponse & {
        items?: Array<RootResponse>;
    };
};

export type ListRootsResponse = ListRootsResponses[keyof ListRootsResponses];

export type CreateRootData = {
    body: CreateRootRequest;
    path?: never;
    query?: never;
    url: '/api/v1/roots';
};

export type CreateRootErrors = {
    /**
     * Invalid input
     */
    400: ErrorResponse;
    /**
     * Root already exists
     */
    409: ErrorResponse;
};

export type CreateRootError = CreateRootErrors[keyof CreateRootErrors];

export type CreateRootResponses = {
    /**
     * Root created
     */
    201: RootResponse;
};

export type CreateRootResponse = CreateRootResponses[keyof CreateRootResponses];

export type NormalizeRootData = {
    body: NormalizeRequest;
    path?: never;
    query?: never;
    url: '/api/v1/roots/normalize';
};

export type NormalizeRootErrors = {
    /**
     * Invalid input
     */
    400: ErrorResponse;
};

export type NormalizeRootError = NormalizeRootErrors[keyof NormalizeRootErrors];

export type NormalizeRootResponses = {
    /**
     * Normalized form
     */
    200: NormalizeResponse;
};

export type NormalizeRootResponse = NormalizeRootResponses[keyof NormalizeRootResponses];

export type DeleteRootData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/roots/{id}';
};

export type DeleteRootErrors = {
    /**
     * Root not found
     */
    404: ErrorResponse;
};

export type DeleteRootError = DeleteRootErrors[keyof DeleteRootErrors];

export type DeleteRootResponses = {
    /**
     * Root deleted
     */
    204: void;
};

export type DeleteRootResponse = DeleteRootResponses[keyof DeleteRootResponses];

export type GetRootByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/roots/{id}';
};

export type GetRootByIdErrors = {
    /**
     * Malformed UUID
     */
    400: ErrorResponse;
    /**
     * Root not found
     */
    404: ErrorResponse;
};

export type GetRootByIdError = GetRootByIdErrors[keyof GetRootByIdErrors];

export type GetRootByIdResponses = {
    /**
     * Root found
     */
    200: RootResponse;
};

export type GetRootByIdResponse = GetRootByIdResponses[keyof GetRootByIdResponses];

export type UpdateRootData = {
    body: UpdateRootRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/roots/{id}';
};

export type UpdateRootErrors = {
    /**
     * Root not found
     */
    404: ErrorResponse;
};

export type UpdateRootError = UpdateRootErrors[keyof UpdateRootErrors];

export type UpdateRootResponses = {
    /**
     * Root updated
     */
    200: RootResponse;
};

export type UpdateRootResponse = UpdateRootResponses[keyof UpdateRootResponses];

export type ListWordsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (1-based)
         */
        page?: number;
        /**
         * Number of items per page
         */
        size?: number;
        /**
         * Arabic text substring search
         */
        q?: string;
        dialect?: Dialect;
        difficulty?: Difficulty;
        partOfSpeech?: PartOfSpeech;
        masteryLevel?: MasteryLevel;
    };
    url: '/api/v1/words';
};

export type ListWordsErrors = {
    /**
     * Invalid query parameters
     */
    400: ErrorResponse;
};

export type ListWordsError = ListWordsErrors[keyof ListWordsErrors];

export type ListWordsResponses = {
    /**
     * Paginated list of words
     */
    200: PaginatedResponse & {
        items?: Array<WordResponse>;
    };
};

export type ListWordsResponse = ListWordsResponses[keyof ListWordsResponses];

export type CreateWordData = {
    body: CreateWordRequest;
    path?: never;
    query?: never;
    url: '/api/v1/words';
};

export type CreateWordErrors = {
    /**
     * Validation error (blank arabicText, unknown enum value)
     */
    422: ErrorResponse;
};

export type CreateWordError = CreateWordErrors[keyof CreateWordErrors];

export type CreateWordResponses = {
    /**
     * Word created
     */
    201: WordResponse;
};

export type CreateWordResponse = CreateWordResponses[keyof CreateWordResponses];

export type AutocompleteWordsData = {
    body?: never;
    path?: never;
    query: {
        q: string;
        limit?: number;
    };
    url: '/api/v1/words/autocomplete';
};

export type AutocompleteWordsErrors = {
    /**
     * Missing required query parameter `q`
     */
    400: ErrorResponse;
};

export type AutocompleteWordsError = AutocompleteWordsErrors[keyof AutocompleteWordsErrors];

export type AutocompleteWordsResponses = {
    /**
     * Matching words (id + arabicText + translation only)
     */
    200: Array<WordAutocompleteResponse>;
};

export type AutocompleteWordsResponse = AutocompleteWordsResponses[keyof AutocompleteWordsResponses];

export type DeleteWordData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/words/{id}';
};

export type DeleteWordErrors = {
    /**
     * Word not found
     */
    404: ErrorResponse;
};

export type DeleteWordError = DeleteWordErrors[keyof DeleteWordErrors];

export type DeleteWordResponses = {
    /**
     * Word deleted
     */
    204: void;
};

export type DeleteWordResponse = DeleteWordResponses[keyof DeleteWordResponses];

export type GetWordByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/words/{id}';
};

export type GetWordByIdErrors = {
    /**
     * Malformed UUID
     */
    400: ErrorResponse;
    /**
     * Word not found
     */
    404: ErrorResponse;
};

export type GetWordByIdError = GetWordByIdErrors[keyof GetWordByIdErrors];

export type GetWordByIdResponses = {
    /**
     * Word found
     */
    200: WordResponse;
};

export type GetWordByIdResponse = GetWordByIdResponses[keyof GetWordByIdResponses];

export type UpdateWordData = {
    body: UpdateWordRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/words/{id}';
};

export type UpdateWordErrors = {
    /**
     * Word not found
     */
    404: ErrorResponse;
    /**
     * Validation error
     */
    422: ErrorResponse;
};

export type UpdateWordError = UpdateWordErrors[keyof UpdateWordErrors];

export type UpdateWordResponses = {
    /**
     * Word updated
     */
    200: WordResponse;
};

export type UpdateWordResponse = UpdateWordResponses[keyof UpdateWordResponses];

export type ListDictionaryLinksData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/words/{id}/dictionary-links';
};

export type ListDictionaryLinksErrors = {
    /**
     * Word not found
     */
    404: ErrorResponse;
};

export type ListDictionaryLinksError = ListDictionaryLinksErrors[keyof ListDictionaryLinksErrors];

export type ListDictionaryLinksResponses = {
    /**
     * List of dictionary links
     */
    200: Array<DictionaryLinkResponse>;
};

export type ListDictionaryLinksResponse = ListDictionaryLinksResponses[keyof ListDictionaryLinksResponses];

export type AddDictionaryLinkData = {
    body: CreateDictionaryLinkRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/words/{id}/dictionary-links';
};

export type AddDictionaryLinkErrors = {
    /**
     * Word not found
     */
    404: ErrorResponse;
    /**
     * Unknown dictionary source
     */
    422: ErrorResponse;
};

export type AddDictionaryLinkError = AddDictionaryLinkErrors[keyof AddDictionaryLinkErrors];

export type AddDictionaryLinkResponses = {
    /**
     * Link added
     */
    201: DictionaryLinkResponse;
};

export type AddDictionaryLinkResponse = AddDictionaryLinkResponses[keyof AddDictionaryLinkResponses];

export type DeleteDictionaryLinkData = {
    body?: never;
    path: {
        id: string;
        linkId: string;
    };
    query?: never;
    url: '/api/v1/words/{id}/dictionary-links/{linkId}';
};

export type DeleteDictionaryLinkErrors = {
    /**
     * Word or link not found
     */
    404: ErrorResponse;
};

export type DeleteDictionaryLinkError = DeleteDictionaryLinkErrors[keyof DeleteDictionaryLinkErrors];

export type DeleteDictionaryLinkResponses = {
    /**
     * Link removed
     */
    204: void;
};

export type DeleteDictionaryLinkResponse = DeleteDictionaryLinkResponses[keyof DeleteDictionaryLinkResponses];

export type GenerateWordExamplesData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/words/{id}/examples';
};

export type GenerateWordExamplesErrors = {
    /**
     * Word not found
     */
    404: ErrorResponse;
    /**
     * AI not configured (OPENROUTER_API_KEY missing)
     */
    503: ErrorResponse;
};

export type GenerateWordExamplesError = GenerateWordExamplesErrors[keyof GenerateWordExamplesErrors];

export type GenerateWordExamplesResponses = {
    /**
     * Two example sentences
     */
    200: ExamplesResponse;
};

export type GenerateWordExamplesResponse = GenerateWordExamplesResponses[keyof GenerateWordExamplesResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthErrors = {
    /**
     * Bad request
     */
    400: unknown;
};

export type GetHealthResponses = {
    /**
     * Server is healthy
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetSwaggerUiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/swagger-ui';
};

export type GetSwaggerUiErrors = {
    /**
     * Bad request
     */
    400: unknown;
};

export type GetSwaggerUiResponses = {
    /**
     * Swagger UI HTML
     */
    200: unknown;
};
